### ISSUE TITLE
Version 2.3

### ISSUE THREAD

**Issue by 304NotModified** [CharsetDetector/UTF-unknown#101]
@rstm-sf Maybe time to release 2.3?

See https://github.com/CharsetDetector/UTF-unknown/milestone/6?closed=1

Thanks for all the work! 🚀

**Comment by rstm-sf** [comment]
Yes, of course :)

Although by and large the changes were related to PATCH, but there are also changes more similar to MINOR

Notes: it would be nice if we got feedback about the change in #97

**Comment by rstm-sf** [comment]
Briefly what changes were made by me:
- `DetectionDetail.EncodingName` property of the result was fixed for codepage .NET name
- For the `iso-2022-ch` encoding name, the  `DetectionDetail.Encoding` property of the result was fixed from `null` to `Encoding.GetEncoding("x-cp50227")`

**Comment by 304NotModified** [comment]
Thanks! I'm currently on a short holiday. Will release a new version when I am back. 

Thanks for the great work!
