### ISSUE TITLE
Would it be possible to publish UTF-unknown as a DLL, too?

### ISSUE THREAD

**Issue by schittli** [CharsetDetector/UTF-unknown#113]
Good morning

Thank you very much for your work and publishing this very useful library!

Would it be possible to publish UTF-unknown as a DLL, so that it can be used by non .net developers, e.g. by PowerShell, too?

Thanks a lot, kind regards,
Thomas

**Comment by rstm-sf** [comment]
Hello!

Alternatively, you [can take dll](https://spin.atomicobject.com/2019/10/21/nuget-package-native-dll/) from the [nuget package](https://www.nuget.org/packages/UTF.Unknown)

**Comment by 304NotModified** [comment]
Yes, unzip the nupgk (rename to .zip first), or use https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
