### ISSUE TITLE
Detected encoding as iso-8859-16 but null Encoding 

### ISSUE THREAD

**Issue by AdamJurga** [CharsetDetector/UTF-unknown#114]
Please see screenshot below.
![image](https://user-images.githubusercontent.com/49482520/94676136-28e48f80-031b-11eb-97e2-5b58850d9a96.png)

From my tests I see that it works fine for many other types of encodings. Only this one is problematic.

**Comment by rstm-sf** [comment]
Hello!

This is ok: there is no object in the dotnet that is iso-8859-16 encoding. The remarks that this library can detect, but not represent in dotnet format, are specified in the [_Docs_](https://github.com/CharsetDetector/UTF-unknown#docs)

**Comment by AdamJurga** [comment]
Sorry, my bad, I ended reading after "Usage" section 🤦‍♂️.  

Is this full list of not available aliases?

- cp949, 
- iso-2022-cn, 
- euc-tw, 
- iso-8859-10, 
- iso-8859-16, 
- viscii, 
- X-ISO-10646-UCS-4-34121/X-ISO-10646-UCS-4-21431

Thanks.

**Comment by rstm-sf** [comment]
> Is this full list of not available aliases?

Yes, these are the encodings that this library can define, but for which there are no implementations. Also, two were replaced with similar ones, at least no one has yet reported that this is incorrect

**Comment by AdamJurga** [comment]
Thank you very much for help!
