### ISSUE TITLE
Consider API breaking changes 

### ISSUE THREAD

**Issue by rstm-sf** [CharsetDetector/UTF-unknown#121]
Hello!

Consider API breaking changes:
- [src/Core](https://github.com/CharsetDetector/UTF-unknown/tree/master/src/Core) as `internal` access
- enable Nullable Reference Types for main source code

It seems to me that the user does not need to have access to the API from the `src/Core` folder. Therefore, to simplify further possible changes to the `src/Core`, it would be good to change to `internal` access. Additionally, NRT support for the remaining API can be added. But there are questions about this, see [this](https://github.com/CharsetDetector/UTF-unknown/pull/116#issuecomment-812678800) comment.

Changes for `src/Core` can be marked in one of the releases as `Obsolete` with a link to this issue for the opportunity to express self-point. Perhaps this could be done for NRT as well?

**Comment by 304NotModified** [comment]
Also we really need an interface an non static methods for mocking :)

**Comment by 304NotModified** [comment]
sounds good, splitted those:

- https://github.com/CharsetDetector/UTF-unknown/issues/148
- https://github.com/CharsetDetector/UTF-unknown/issues/147
