### ISSUE TITLE
DetectFromString

### ISSUE THREAD

**Issue by foxi69** [CharsetDetector/UTF-unknown#122]
is it possible to detect from string then convert it for the better encoding?

**Comment by rstm-sf** [comment]
In the .NET, string is always utf-16 encoded. Therefore, from string we can always get the required byte array.

The approach in this library does not give 100% results. Therefore, I see no reason to add such functionality to the core library

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
