### ISSUE TITLE
How to use it with powershell/core script

### ISSUE THREAD

**Issue by dahikino** [CharsetDetector/UTF-unknown#123]
Hello,

I try to load the dll as module but i can't find the way to use the class CharsetDetector, with issue result : 
**_New-Object: A constructor was not found. Cannot find an appropriate constructor for type UtfUnknown.CharsetDetector._**

Have you any idea how to do it ?

Best regards

**Comment by rstm-sf** [comment]
Hi, could you please provide an example?

**Comment by dahikino** [comment]
Finally i i found how to do it in a file script: 
```
Add-Type -Path .\UtfUnknown.dll
[UtfUnknown.CharsetDetector]::DetectFromFile($filePath)
```
This is a example for the method DetectFromFile.
If you want only the code charset : 
```
Add-Type -Path .\UtfUnknown.dll
[UtfUnknown.CharsetDetector]::DetectFromFile($filePath).detected.EncodingName.ToString()
```

**Comment by dahikino** [comment]
More generally, the syntax using .Net library in Powershell is :
[namespace.classname]::method

**Comment by 304NotModified** [comment]
Thanks for sharing!

**Comment by 304NotModified** [comment]
Closing as self answered. Thanks again :)
