### ISSUE TITLE
Detected encoding is wrong with DetectFromBytes, ok with other methods for UTF-8 file containing emoji

### ISSUE THREAD

**Issue by fretman92** [CharsetDetector/UTF-unknown#38]
Test program launched from latest source:

```c#
            string filename = args[0];

            var result = CharsetDetector.DetectFromFile(filename);

            if (result.Detected != null)
            {
                Console.WriteLine("DetectFromFile - Charset: {0}, confidence: {1}", result.Detected.EncodingName, result.Detected.Confidence);
            }

            byte[] bytes = System.IO.File.ReadAllBytes(filename);
            result = CharsetDetector.DetectFromBytes(bytes);

            if (result.Detected != null)
            {
                Console.WriteLine("DetectFromBytes - Charset: {0}, confidence: {1}", result.Detected.EncodingName, result.Detected.Confidence);
            }

            System.IO.Stream fileStream = System.IO.File.OpenRead(filename);
            result = CharsetDetector.DetectFromStream(fileStream);

            if (result.Detected != null)
            {
                Console.WriteLine("DetectFromStream - Charset: {0}, confidence: {1}", result.Detected.EncodingName, result.Detected.Confidence);
            }

```

Result:
![image](https://user-images.githubusercontent.com/305637/29879908-b6486e48-8da6-11e7-874b-399c3b502350.png)

The file is a HTML UTF-8 (without BOM) encoded file containing 1 simple emoji : 😀
(attached in the zip below) 
[utf8_with_emoji.zip](https://github.com/CharsetDetector/UTF-unknown/files/1264089/utf8_with_emoji.zip)

Why does the `DetectFromBytes` method gives a different result?

**Comment by 304NotModified** [comment]
> Why does the `DetectFromBytes` method gives a different result?

Need some time, but figured something out 
- The detect stream read in buffers of 1024 bytes. After 3 cycles, it's convinced it's UTF-8
- The detect bytes reads all bytes (as they al already in memory) (73939 bytes), and after that It don't think it's ut8
--

Now we have to check why it's after 3072 bytes UTF-8 and not after 73939 bytes.

**Comment by 304NotModified** [comment]
it failes at first at bytecount 73837

**Comment by 304NotModified** [comment]
F0 9F 98 80 is not recognized as utf8 :(

**Comment by rstm-sf** [comment]
In general, emoji is another logic :)

**Comment by rstm-sf** [comment]
Maybe can come up with a table of special characters that you need to skip in a certain scenario

**Comment by 304NotModified** [comment]
replaced with https://github.com/CharsetDetector/UTF-unknown/issues/149
