### ISSUE TITLE
"X-ISO-10646-UCS-4-2413" or "X-ISO-10646-UCS-4-2143"?

### ISSUE THREAD

**Issue by msdobrescu** [CharsetDetector/UTF-unknown#41]
There is a typo in the encodings and differs from the charsets class.

It is listed "X-ISO-10646-UCS-4-2413" and "X-ISO-10646-UCS-4-2143".

Please fix this.

A good practice is to use the defined constants instead of local strings.

**Comment by 304NotModified** [comment]
Thanks for reporting!

**Comment by 304NotModified** [comment]
I think I should release a RTM ;)

**Comment by msdobrescu** [comment]
You're welcome!

**Comment by 304NotModified** [comment]
where did you find this? can't find `4-2413` in the source

**Comment by msdobrescu** [comment]
Of course you don't, it was in the tests/Charsets.cs file, but was removed by the last commit.

**Comment by 304NotModified** [comment]
so this is fixed?

**Comment by msdobrescu** [comment]
Yes.

**Comment by 304NotModified** [comment]
👍
