### ISSUE TITLE
Not working on .NET Core 3.0

### ISSUE THREAD

**Issue by pcfulife** [CharsetDetector/UTF-unknown#51]
Hello, I am handling many CJK files. In .NET Framework 4.7.2, it works well. But, when I ported to .NET Core 3.0, CharsetDetector.DetectFromStream(fs).Detected returns null at most case.

I think that it is not a bug of UTF.Unknown. Because, all packages that uses or ported from UDE have same problems. But, I found that currently developing package is only UTF.Unknown. So, I post it.
I already installed System.Text.Encoding.Codepages (v4.6.0-preview.19073.11). And, I am using .NET Core 3.0.100-previre4-010381

Thanks.

**Comment by 304NotModified** [comment]
Thanks for the info.

I think (also) this could not be an issue from the library - as it's written to .NET Standard and not specific for .NET Core

**Comment by rstm-sf** [comment]
Hello!

I think the library can support .NET Core. But for this, we need to install the [`System.Text.Encoding.Codepages` (>= .NETStandard 1.3, >= .NETFramework 4.6, >=.NETCoreApp 2.0)](https://www.nuget.org/packages/System.Text.Encoding.CodePages/) package and use it. And write where need it, for example
```c#
#if NETSTANDARD1_3
    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
#endif
```

**Comment by rstm-sf** [comment]
If I understand correctly, for this we need to first extract `UtfUnknown.Core` to a separate project, and the rest create separate projects for different versions of .NET

**Comment by 304NotModified** [comment]
If this is needed, then we could target the project also to .net core 3.  No need for a separate project. 

The project is already a multi target one, see https://github.com/CharsetDetector/UTF-unknown/blob/99a2bd1667e4dd8e0383655f2a86625239aa368c/src/UTF-unknown.csproj#L4

**Comment by rstm-sf** [comment]
@304NotModified ok, thanks!

**Comment by rstm-sf** [comment]
As I understand that with .NET Core 3.0 don't need add link to `System.Text.Encoding.Codepages` separately: dotnet/corefx#38357
