### ISSUE TITLE
Failed to detetect Japanese text encoding utf-16le

### ISSUE THREAD

**Issue by rstm-sf** [CharsetDetector/UTF-unknown#72]
Hello!

Failed to detetect Japanese text encoding utf-16le.

[lang_ja_utf-16le.txt](https://github.com/CharsetDetector/UTF-unknown/files/3774978/lang_ja_utf-16le.txt)

`result.Detected` was null.

**Comment by rstm-sf** [comment]
As I understand it, is encoding without BOM

**Comment by rstm-sf** [comment]
@304NotModified, hello!

You do not know why the `UCS2LE_SMModel` and `UCS2BE_SMModel` models exist, but are not used anywhere?

**Comment by rstm-sf** [comment]
> As I understand it, is encoding without BOM

then #5

**Comment by 304NotModified** [comment]
> You do not know why the `UCS2LE_SMModel` and `UCS2BE_SMModel` models exist, but are not used anywhere?

Sounds like a bug, or maybe an encoding that isn't available in .NET. But those are guesses.

**Comment by rstm-sf** [comment]
>[**Q:** ___What is the difference between UCS-2 and UTF-16?___](http://www.unicode.org/faq/utf_bom.html#utf16-11)
**A:** UCS-2 is obsolete terminology which refers to a Unicode implementation up to Unicode 1.1, before surrogate code points and UTF-16 were added to Version 2.0 of the standard. This term should now be avoided.
UCS-2 does not describe a data format distinct from UTF-16, because both use exactly the same 16-bit code unit representations. However, UCS-2 does not interpret surrogate code points, and thus cannot be used to conformantly represent supplementary characters.
Sometimes in the past an implementation has been labeled "UCS-2" to indicate that it does not support supplementary characters and doesn't interpret pairs of surrogate code points as characters. Such an implementation would not handle processing of character properties, code point boundaries, collation, etc. for supplementary characters.

**Comment by rstm-sf** [comment]
I wonder if they can be used to detect utf-16?

I just did not observe such models in other projects

**Comment by rstm-sf** [comment]
> then #5

I think this one should be closed as a duplicate
