### ISSUE TITLE
Change codepage name 'mac-centraleurope' to 'x-mac-ce'

### ISSUE THREAD

**Issue by rstm-sf** [CharsetDetector/UTF-unknown#75]
Hello!

Change codepage name 'mac-centraleurope' to 'x-mac-ce'.

Because in .NET so (see [code-page-identifiers](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers) or [EncodingTable.Data.cs](https://github.com/dotnet/corefx/blob/8d5c5f548deafb7cd5e6428f12152c339c672228/src/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs)).

**Comment by 304NotModified** [comment]
If we do `Encoding.GetEncoding`, will the latter retrieve an encoding? And the first?

**Comment by rstm-sf** [comment]
> If we do `Encoding.GetEncoding`, will the latter retrieve an encoding?

Yes (see [doc](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers) or [example-on-sharplab](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYwCYgNQB8ACATAIwCwAUPgAwAE+xAdACoCmYcA3BRfgMx2EaAYQoBvCjUkDCEqePJTFdYgE4AFAFFUAYwD2GAJaoA5gwDiLOFr2GTagERgAtAFsAhtqfaW9gJQMAdRZgADk3FxZfLgUpAF8KWKA=)).

> And the first?

I think this is true for non win32 APIs

**Comment by rstm-sf** [comment]
Now it's part #78
