### ISSUE TITLE
Refactor ctor DetectionDetail: not all codepage names are supported by .NET

### ISSUE THREAD

**Issue by rstm-sf** [CharsetDetector/UTF-unknown#78]
Hello!

Refactor ctor DetectionDetail(string, float, CharsetProber, TimeSpan?, string): not all codepage names are supported by .NET.

Code like `Split('(').First().Trim()` looks redundant.

To do this, will need to consider that not all codepage names are supported by .NET (see `CodepageName` by #74). Also, it will be necessary to indicate explicitly in the `readme` that not all `Encoding` exists.

And maybe it will be possible to get rid of try / catch?

- [ ] Resolve __TODO__ in `CodepageName.cs`
  - [x] Resolve #75 
  - [x] Resolve #82 
  - [ ] Not supported _iso-2022-ch_? Maybe fix to _x-cp50227_?
  - [x] Not supported _CP949_? Attention!: it is superset of _ks_c_5601-1987_ (see https://github.com/CharsetDetector/UTF-unknown/pull/74#issuecomment-550362133)
  - [ ] `TODO: Not supported?` -- If possible, get rid of all such or process separately
  - [x] `TODO: Are other aliases ... ` (I think can simply remove `TODO:` because important identifier)
- [ ] \(Optional) to get rid of `try / catch` in ctor DetectionDetail
- [ ] Update `README.md`

**Comment by 304NotModified** [comment]
> Also, it will be necessary to indicate explicitly in the `readme` that not all `Encoding` exists.

Sounds good!



> And maybe it will be possible to get rid of try / catch?

That would be nice if it's 100% safe

**Comment by rstm-sf** [comment]
> That would be nice if it's 100% safe

Class `CodepageName` was created based on .net core source :)

https://github.com/CharsetDetector/UTF-unknown/blob/cc2b081a621001aedfac20229bd555585d366e9f/src/Core/CodepageName.cs#L33-L36

All unsupported can be added to some object and check before calling `Encoding.GetEncoding(string)`

**Comment by 304NotModified** [comment]
Nice! I checked a lot of files, but missed that :angel:

**Comment by rstm-sf** [comment]
- [ ] Resolve __TODO__ in `CodepageName.cs`
  - [ ] Resolve #75 
  - [ ] Resolve #82 
  - [ ] Not supported _iso-2022-ch_? Maybe fix to _x-cp50227_?
  - [ ] Not supported _CP949_? Attention!: it is superset of _ks_c_5601-1987_ (see https://github.com/CharsetDetector/UTF-unknown/pull/74#issuecomment-550362133)
  - [ ] `TODO: Not supported?` -- If possible, get rid of all such or process separately
  - [ ] `TODO: Are other aliases ... ` (I think can simply remove `TODO:` because important identifier)
- [ ] Update `README.md`

**Comment by rstm-sf** [comment]
> Not supported iso-2022-ch? Maybe fix to x-cp50227?

see

https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers

https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/mscorlib/system/text/iso2022encoding.cs#L30

https://github.com/dotnet/corefx/blob/cf28b7896a762f71c990a5896a160a4138d833c9/src/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs#L342

https://github.com/dotnet/corefx/blob/cf28b7896a762f71c990a5896a160a4138d833c9/src/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs#L65

https://github.com/mirror/reactos/blob/c6d2b35ffc91e09f50dfb214ea58237509329d6b/reactos/dll/win32/kernel32/winnls/lang/en-US.rc#L153-L154

**Comment by rstm-sf** [comment]
Sorry, but the tasks is not yet completed. I wait #86
