### ISSUE TITLE
Add detect encoding with BOM: UTF-7 and GB-18030

### ISSUE THREAD

**Issue by rstm-sf** [CharsetDetector/UTF-unknown#79]
Hello!

Add detect encoding with BOM: UTF-7 and GB-18030.

It seems that this can be done if you believe the table from the [wiki](https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding)

**UTF-7**:
- `2B 2F 76 38` (`43 47 118 56`)
- `2B 2F 76 39` (`43 47 118 57`)
- `2B 2F 76 2B` (`43 47 118 43`)
- `2B 2F 76 2F` (`43 47 118 47`)
- `2B 2F 76 38 2D` (`43 47 118 56 45`)

**GB-18030**:
- `84 31 95 33` (`132 49 149 51`)

**Comment by 304NotModified** [comment]
Sounds good to me! I think it's wise to add the link to the comments in code for this.
