### ISSUE TITLE
Upgrade target .NET Framework 4.0 to 4.5.2

### ISSUE THREAD

**Issue by rstm-sf** [CharsetDetector/UTF-unknown#85]
Hello!

Maybe upgrade target .NET Framework 4.0 to 4.5.2 in version 3.*?

https://github.com/CharsetDetector/UTF-unknown/blob/cc2b081a621001aedfac20229bd555585d366e9f/src/UTF-unknown.csproj#L4

Because MS don't support (see [Lifecycle FAQ—.NET Framework](https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework)) and some optimizations

**Comment by 304NotModified** [comment]
What kind of optimizations your thinking of?

I prefer keeping 4.0 if it's still working.

**Comment by rstm-sf** [comment]
For example, in 4.5.1 [GC performance has been improved](https://devblogs.microsoft.com/dotnet/net-framework-4-5-1-rtm-start-coding/)

[Release notes 4.5](https://github.com/Microsoft/dotnet/tree/master/releases/net45/README.md)
[Release notes 4.5.1](https://github.com/Microsoft/dotnet/tree/master/releases/net451/README.md)
[Release notes 4.5.2](https://github.com/Microsoft/dotnet/tree/master/releases/net452/README.md)

**Comment by 304NotModified** [comment]
Yes, but if a user uses .net 4.5.1, that works without changing this library.

**Comment by rstm-sf** [comment]
@304NotModified, Ok. Sorry, I am not so good at this yet, but I have read the [documentation](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/version-compatibility) and it suited me. I was still just embarrassed that I could not use the optional features of the frameworks :)

I think it can be closed then
